### PR TITLE
Khanh/refactor

### LINKED ISSUE #24: Implement paginations for folders

### LINKED ISSUE #25: Implement paginations for requests

### LINKED ISSUE #26: Implement root dashboard for staff

### LINKED ISSUE #27: Implement root dashboard for employee

### LINKED ISSUE #28: Refactor pagination

### LINKED ISSUE #29: Refactor selection on table

### LINKED ISSUE #30: Add search for lockers/folders/documents

### LINKED ISSUE #31: Update borrow and return document logic for staff

### LINKED ISSUE #32: Update borrow flow for employee based on status

### LINKED ISSUE #33: Add loading skeleton while fetching

### PR DESCRIPTION
**Pull request by khanhngn-dev**

### CODE REVIEW

**Review by ChienNQuang — CHANGES_REQUESTED** [review]
so many js!

**Review by kaitoz11 — APPROVED** [review]
Pray for your hard works

**Review by ChienNQuang — APPROVED** [review]
oh it's typescript nvm

**Review by vzart — APPROVED** [review]
LGTM! pray for your soul

**Review by StarryFolf — APPROVED** [review]
:3

**Pull request merged**
